version: 13.7.{build}

configuration:
  - Release

image:
  - Visual Studio 2022

environment:
  NSISDIR: C:\Program Files (x86)\NSIS
  OPENSSLDIR: C:\OpenSSL-v111-Win64\bin
  matrix:
  - QTDIR: C:\Qt\5.15\msvc2019_64
  - QTDIR: C:\Qt\6.5\msvc2019_64
    NSISDEF: /DQT6

install:
- cmd: |-
    set PATH=%QTDIR%\bin;%NSISDIR%;%PATH%
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat

build_script:
- cmd: |-
    lrelease gpxsee.pro
    qmake gpxsee.pro
    nmake release

    md installer
    copy release\GPXSee.exe installer
    windeployqt --release installer\GPXSee.exe
    copy pkg\windows\gpxsee64.nsi installer
    xcopy data\CRS installer\CRS /i
    xcopy data\maps installer\maps /i
    xcopy lang\*.qm installer\translations\ /sy
    xcopy icons\symbols installer\symbols /i
    copy licence.txt installer
    copy %OPENSSLDIR%\libcrypto-1_1-x64.dll installer
    copy %OPENSSLDIR%\libssl-1_1-x64.dll installer

    makensis.exe %NSISDEF% installer\gpxsee64.nsi

artifacts:
- path: installer\GPXSee-*.exe
