language: c++

os:
  - linux
  - osx

dist: focal
osx_image: xcode12

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cleanup; fi

addons:
  homebrew:
    packages:
    - qt
  apt:
    packages:
    - qtbase5-dev
    - qtbase5-private-dev
    - libqt5opengl5-dev
    - qttools5-dev-tools

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH=/usr/local/opt/qt/bin/:${PATH}; fi
  - lrelease gpxsee.pro
  - qmake gpxsee.pro
  - make
