name: Android

on:
  push:
    branches:
      - master

jobs:
  build:
    name: GPXSee
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Run sdkmanager update
        run:  ${ANDROID_HOME}/tools/bin/sdkmanager --update
      - name: Install android platform, platform-tools, build-tools and ndk
        run:  ${ANDROID_HOME}/tools/bin/sdkmanager --install "cmdline-tools;latest" "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;22.1.7171670"
      - name: Install Qt (Desktop)
        uses: jurplel/install-qt-action@v2
        with:
          aqtversion: '==2.1.0'
          version: '6.3.0'
      - name: Install Qt (Android)
        uses: jurplel/install-qt-action@v2
        with:
          aqtversion: '==2.1.0'
          version: '6.3.0'
          target: 'android'
          arch: 'android_armv7'
          modules: qtpositioning qt5compat
      - name: Install Android OpenSSL
        run:  git clone https://github.com/KDAB/android_openssl.git
      - name: Configure build
        run:  qmake gpxsee.pro OPENSSL_PATH=android_openssl
      - name: Build project
        run:  make -j2 apk
