name: OS X

on:
  push:
    branches:
      - master

jobs:
  build:
    name: GPXSee
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install qt5
      - name: Create localization
        run: lrelease gpxsee.pro
      - name: Configure build
        run: qmake gpxsee.pro
      - name: Build project
        run: make -j3
