name: OS X

on:
  push:
    branches:
      - master

jobs:
  qt5:
    name: GPXSee Qt5 build
    runs-on: macos-latest
    steps:
      - name: Set environment variables
        run: echo "PATH=/usr/local/opt/qt@5/bin:$PATH" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install qt5
      - name: Create localization
        run: lrelease gpxsee.pro
      - name: Configure build
        run: qmake gpxsee.pro
      - name: Build project
        run: make -j3
      - name: Create DMG
        run: macdeployqt GPXSee.app -dmg
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GPXSee-qt5.dmg
          path: GPXSee.dmg

  qt6:
    name: GPXSee Qt6 build
    runs-on: macos-latest
    steps:
      - name: Set environment variables
        run: echo "PATH=/usr/local/opt/qt@6/bin:$PATH" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install qt6
      - name: Create localization
        run: lrelease gpxsee.pro
      - name: Configure build
        run: qmake gpxsee.pro
      - name: Build project
        run: make -j3
      - name: Create DMG
        run: macdeployqt GPXSee.app -dmg
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GPXSee-qt6.dmg
          path: GPXSee.dmg
